#!/usr/bin/env python

import numpy as np
import rospy
import cv2
from std_msgs.msg import String
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError

class FlowingComment:
    def __init__(self):
        self.im_pub = rospy.Publisher("flowing", Image, queue_size=1)
        self.bridge = CvBridge()
        self.im_sub = rospy.Subscriber('cv_camera/image_raw', Image, self.callback)
        #self.sub = rospy.Subscriber('sentence', str, self.FlowingComment)

    def callback(self, data):
        try:
            img = self.bridge.imgmsg_to_cv2(data, "bgr8")
        except CvBridgeError as e:
            print(e)
        comment = "Robot System 2016"
        font = cv2.FONT_HERSHEY_PLAIN
        pub_img = cv2.putText(img,comment,(100,100),font, 3,(255,0,0),5)
        
        try:
            self.im_pub.publish(self.bridge.cv2_to_imgmsg(pub_img, "bgr8"))
        except CvBridgeError as e:
            print(e)


if __name__ == '__main__':
    fc = FlowingComment()
    rospy.init_node('flowing_message', anonymous=True)
    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down")
    #image = np.zeros((rows, cols, 3), np.uint8)

